In [1]:
import numpy as np

Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
a = np.array([[1, 2, 3, 3, 1], 
              [6, 8, 11, 10, 7]])
mean_a = np.mean(a, axis = 1)#, keepdims = True)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [3]:
a_centered = np.concatenate((a[0, 0:] - mean_a[0], a[1, 0:] - mean_a[1]), axis = 0).reshape(2, 5)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [81]:
a_centered_sp = a_centered[0:, 0] @ a_centered[0:, 1]
a_centered_sp = np.dot(a_centered_sp, a_centered[0:, 2])
a_centered_sp = a_centered_sp @ a_centered[0:, 3]
a_centered_sp = np.dot(a_centered_sp, a_centered[0:, 4])
a_centered_sp
# не успел доделать

array([-4.9536 , -6.93504])

In [74]:
# попробовал то же самое, но другим способом
a_centered_sp = a_centered[0:, 0]
for i in range(1, len(a_centered.T)):
    a_centered_sp = np.dot(a_centered[0:, i], a_centered_sp)
a_centered_sp

array([-4.9536 , -6.93504])